# Generated by Django 3.0.8 on 2020-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_task_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='storyPoints',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
